# Generated by Django 5.2.7 on 2025-10-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
    ]
